// AUTO-GENERATED by tools/csv_to_wrecks_data.py — do not edit by hand.
const FIELDWORK_PHOTOS    = ["IMG_3666.webp", "IMG_4395.webp", "IMG_4400.webp", "IMG_5237.webp", "IMG_5690.webp", "anna.webp", "annamap.webp", "george.webp", "irene_ss.webp", "james.webp", "jamesflag.webp", "nanigeorge.webp", "naniphil.webp", "phildaltonick.webp", "priya.webp", "rov1.webp", "wreck__.webp"];
const JOURNEY_PHOTOS      = ["IMG_5748.webp", "anna.webp", "george.webp", "george2.webp", "james.webp", "nanigeorge.webp", "rov1.webp"];
const ABOUT_PHOTOS        = ["IMG_4065.webp", "IMG_4401.webp", "IMG_5237.webp", "IMG_5673.webp", "IMG_5683.webp", "IMG_5690.webp", "IMG_5756.webp", "PhilROV.webp", "george2.webp"];
const ARCHIVE_CSV_FILENAME = "target_master_archive_10Aug2026.csv";
