// AUTO-GENERATED by tools/csv_to_wrecks_data.py — do not edit by hand.
const FIELDWORK_PHOTOS = ["IMG_3666.jpg", "IMG_4395.jpg", "IMG_4400.jpg", "IMG_4401.jpg", "anna.jpg", "annamap.jpg", "george.jpg", "george2.jpg", "irene_ss.png", "james.jpg", "rov1.jpg", "wreck__.jpg"];
const JOURNEY_PHOTOS   = ["anna.jpg", "george.jpg", "george2.jpg", "james.jpg", "rov1.jpg"];
